- .travis.yml
- environment.yml
This is a short-term fix, but for now we upgrade pymca to the one on my fork. I added some new parameters into pymca and this made the tests fail.
> Fix build by adding an upgrade to travis

- .travis.yml
- environment.yml
- savu/plugins/filters/paganin_filter.py
- savu/plugins/utils.py
- savu/test/travis/configurator_tests/dawn_compatible_test.py
- scripts/configurator_tests/dawn_compatible_test.py
- scripts/configurator_tests/savu_config_test.py
This fixes the issue with the dawn_compatible decorator, and adds a new set of tests for the configurator and the decorator.
> Dawn compatible

- savu/plugins/corrections/camera_rot_correction.py
- savu/plugins/savers/extended_tiff_saver.py
Modified tiff_saver to allow adding the scanname to the output file name and include leading zeros for the numbers.
> Added camera_rot_correction plugin.

- .travis.yml
- savu/plugins/filters/pymca.py
Remove print blocking statements, as PyMca will no longer print logging messages to stdout from within McaAdvancedFitBatch
> SCI-6241: Mitigate PyMCA console output

- savu/core/transports/dosna_transport.py
- savu/data/transport_data/dosna_transport_data.py
- savu/tomo_recon.py
- Create associated DosNa transport and data classes
- Parse parameters used for creating the connection
> DosNa integration

- Dockerfile
* Updated Repository
* Created version vars for making it easier to rebuild 
* Removed a few temporary steps added for testing
> Updated docker file for external use

- savu/data/data_structures/data_types/fabIO.py
- savu/plugins/loaders/full_field_loaders/image_loader.py
- savu/tomo_recon.py
- Corrects a few instances of forward slash assumptions that caused issues on Windows
- Made execution of the TomoPy unit test dependent on TomoPy being installed
> Fix a couple of Windows compatibility issues

- bin/savu_mpijob.sh
> Delete unused lines

- savu/core/transports/dosna_transport.py
Savu doesn't recognize a parameter due to this typo
> Fix mistyped option

- savu/data/plugin_list.py
This change makes GPU dependencies optional if you are not using GPU
plugins
> Don't fail GPU check when not using GPU processes

- savu/plugins/filters/hilbert_filter.py
Changed self.filter to self.filter1
added two sentences of descriptions
> small change of hilbert filter

- savu/plugins/filters/hilbert_filter.py
Sorry! Found an error after reconstructed more data!
>  Correct hilbert filter: changed center of coordinates 

- savu/plugins/ring_removal/remove_unresponsive_and_fluctuating_rings.py
> Add algorithm 6 for removing dead rings

- savu/plugins/corrections/convert_360_180_sinogram.py
For some reasons it was not on github but in /pre-release internal files
> Add 360-180 converter again

- savu/plugins/centering/vo_centering.py
Improve the reliability of fine-search.
Add options to broadcast previewed values of CoRs to a full dataset.
+ 'median': using the median value
+ 'mean': using the mean value
+ 'nearest': using nearest value
+ ''linear_fit: using linear fit
Add warning messages if the best CoR may be out of the searching range.
Add option to use averaging of several nearby sinograms to calculate CoR to improve SNR
Change downsampling method.
Improve the codes...
> Improve autocentering method

- savu/plugins/segmentation/morph_snakes.py
- savu/plugins/segmentation/morph_snakes3D.py
- savu/plugins/segmentation/morphological_operations/__init__.py
- savu/plugins/segmentation/morphological_operations/morph_proc.py
* 2D/3D Morphological snakes wrapped (https://github.com/pmneila/morphsnakes)
* Morphological processing operations for binary/grayscale using skimage.morphology
> Morphological snakes + morphological processing 

- savu/plugins/basic_operations/get_data_statistics.py
plugin to calculate global statistics (max, min sum, mean) of the input data (3D,4D) and save it to METADATA
> get data statistics plugin

- savu/plugins/segmentation/mask_evolve.py
Savu wrapping a new method from i23seg
https://github.com/dkazanc/i23seg
> a wrapper around flat segment plugin

- environment.yml
All should be in order now to use the newer version from the channel
> tomobar roll to a newer version

- savu/plugins/centering/vo_centering.py
This parameter helps to improve SNR it should be used as default.
> Update a default parameter of autocentering

- savu/plugins/reconstructions/tomobar/__init__.py
- savu/plugins/reconstructions/tomobar/tomobar_recon.py
- savu/plugins/reconstructions/tomobar/tomobar_recon_3D.py
- savu/plugins/reconstructions/tomobar/tomobar_recon_cpu.py
- savu/plugins/reconstructions/tomobar/tomobar_recon_fully3D.py
New 3D tomobar plugin which enables 3D reconstruction across multiple GPUs
thanks @nicwade
> new tomobar 3D plugin

- .circleci/config.yml
This should fix the Singularity images build failing
> Circle-CI: use httplib2==0.15.0

- savu/plugins/reconstructions/tomobar/tomobar_recon_3D.py
Fixes a bad indent that was causing a travis build error https://travis-ci.com/github/dtasev/Savu/builds/162435868#L4761
> Fixes bad indent and removes spaces from empty lines

- Jenkinsfile
- install/savu_lite27/.condarc
- install/savu_lite27/build.sh
- install/savu_lite27/instructions.txt
- install/savu_lite27/meta.yaml
- Savu-lite py27 install recipes 
- JenkinsFile to trial Jenkins build for savu-lite
> Savu-lite py27 install recipes 

- savu/test/test_process_list_utils.py
- setup.py
Adds a new function that picks up all files in the target folder. 
This is used to construct the `test_data` packaging list, and will include all files (`nxs`, `h5`, `yml`) present in the `test_data` folder
> Adds h5 to the list of files gathered, so that the data is properly packaged

- savu/test/base_checkpoint_test.py
- savu/test/travis/plugin_tests/loader_tests/template_loader_test.py
making delete of folders more flexible to deal with Jenkins server behaviour
> adding rmtree with ignore flag

- install/savu_hpc/conda-recipes/tomophantom/meta.yaml
- install/savu_hpc/savu_installer/check_package.sh
- install/savu_hpc/savu_installer/savu_installer.sh
- install/savu_hpc/savu_installer/versions_file.txt
a modified installer to check that each new package is installed correctly into conda environment before proceeding.
> Conda checks for correctly installed packages

- .github/workflows/savu_full_tests.yml
- README.rst
fixing obsolete/not working badges and adding Github Actions badge
> fixing main page badges

- install/savu_lite37/spec-savu3_0_lite_master.txt
- savu/plugins/simulation/tomo_phantom.py
- savu/test/travis/plugin_tests/simulation_tests/tomophantom_test.py
updates tomophantom plugin to changes in software
> updates to tomophantom plugin

- savu/plugins/reshape/image_stitching.py
(cherry picked from commit 23f75151069da58efa837bf22a1ea81f64429bbf)
> Adds missing fixed_length key word to input plugin dataset in image stitching plugin

- savu/plugins/loaders/utils/my_safe_constructor.py
- savu/plugins/loaders/utils/my_safe_loader.py
- savu/plugins/loaders/utils/yaml_utils.py
- savu/plugins/reconstructions/tomobar/tomobar_recon_3D_tools.py
- savu/plugins/reconstructions/tomobar/tomobar_recon_cpu_tools.py
- savu/plugins/reconstructions/tomobar/tomobar_recon_tools.py
- savu/plugins/utils.py
SafeConstructor added to prevent on and off from being changed to boolean values
> Prevent on and off from being changed to boolean

- savu/plugins/reconstructions/astra_recons/astra_recon_cpu_tools.py
- savu/plugins/reconstructions/astra_recons/base_astra_recon.py
- savu/plugins/reconstructions/astra_recons/base_astra_vector_recon.py
- savu/plugins/reconstructions/base_recon.py
- scripts/config_generator/arg_parsers.py
- scripts/config_generator/content.py
- scripts/config_generator/savu_config.py
> jira bug fixes

- doc/source/reference/plugin_documentation/plugins/filters/dezingers/dezinger.rst
- doc/source/reference/plugin_documentation/plugins/filters/dezingers/dezinger_gpu.rst
- doc/source/reference/plugin_documentation/plugins/reconstructions/astra_recons/astra_recon_cpu.rst
- doc/source/reference/savu_commands/savu_refresh.rst
- scripts/config_generator/display_formatter.py
- scripts/config_generator/savu_config.py
- scripts/configurator_tests/refresh_process_lists_test.py
- setup.py
- Alter the width of the display
> Add savu_refresh command to update process lists

- savu/core/transport_setup.py
- savu/data/experiment_collection.py
- savu/test/base_checkpoint_test.py
- savu/test/test_utils.py
- savu/tomo_recon.py
- scripts/citation_extractor/citation_extractor.py
- scripts/dawn_runner/run_savu.py
I have removed the run_log to prevent errors, as the mpi_log branch was not building correctly before the weekend.
> Remove run_log directory, run_command file and command from tests

- savu/data/stats/statistics.py
Quick fix for issue to do with patterns in the statistics class.
> stats pattern fix
